// Generated by icomoon_selection_gen, do not modify by hand

// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class Icomoon {
  Icomoon._();

  static const _kFontFam = 'Icomoon';

  static const IconData closed_eye = IconData(0xe900, fontFamily: _kFontFam);

  static const IconData column = IconData(0xe901, fontFamily: _kFontFam);

  static const IconData deposited = IconData(0xe903, fontFamily: _kFontFam);

  static const IconData etherum = IconData(0xe906, fontFamily: _kFontFam);

  static const IconData grid = IconData(0xe90b, fontFamily: _kFontFam);

  static const IconData open_eye = IconData(0xe90e, fontFamily: _kFontFam);

  static const IconData profile = IconData(0xe910, fontFamily: _kFontFam);

  static const IconData sent = IconData(0xe911, fontFamily: _kFontFam);

  static const IconData settings = IconData(0xe912, fontFamily: _kFontFam);

  static const IconData transaction_received =
      IconData(0xe914, fontFamily: _kFontFam);

  static const IconData transaction_sent =
      IconData(0xe915, fontFamily: _kFontFam);

  static const IconData trends = IconData(0xe916, fontFamily: _kFontFam);

  static const IconData verified = IconData(0xe917, fontFamily: _kFontFam);

  static const IconData withdrawal = IconData(0xe919, fontFamily: _kFontFam);
}
